version: '3'
services:
    web:
        build: .
        ports:
            - "127.0.0.1:9000:9000"
        volumes:
            - ./config.py:/code/config.py
    redis:
        image: "redis:alpine"
        volumes:
            - ./data:/data
